#
#
# Copyright 2016 The Symphony Software Foundation
#
# Licensed to The Symphony Software Foundation (SSF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

language: java

install: true
script:
- "if [[ $TRAVIS_BRANCH =~ master ]]; then mvn clean install ; fi"

jdk:
  - oraclejdk8

# Coverity scan has has a low rate limit, compared to the builds run by (all) the Foundation projects
# It can be enabled for demo purposes or on stable branches (to lower build frequency)
# It is disencouraged to enable it on active branches, as it may lead to frequent and unexpected build failures
#
# addons:
#   coverity_scan:
#     project:
#       name: "symphonyoss/app-auth-example"
#       description: "Build submitted via Travis CI"
#     notification_email: infra@symphony.foundation
#     build_command_prepend: "mvn clean"
#     build_command: "mvn package"
#     branch_pattern: master
